jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

server:
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securityEx?serverTimezone=Asia/Seoul
    username: yeonable
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  redis:
    host: localhost
    port: 6379



logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: INFO
    org.springframework.web: DEBUG
#    org.hibernate.orm.jdbc.bind: trace





#logging:
#  level:
#    org.hibernate.SQL: debug